package com.lee.tac.dto;

import java.io.Serializable;

public class TestcaseStatusDto implements Serializable {

    private static final long serialVersionUID = 2841075950677922303L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_status.name
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_status.code
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    private String code;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_status.name
     *
     * @return the value of case_status.name
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_status.name
     *
     * @param name the value for case_status.name
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_status.code
     *
     * @return the value of case_status.code
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_status.code
     *
     * @param code the value for case_status.code
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_status.description
     *
     * @return the value of case_status.description
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
}