package com.lee.tac.model;

public class TestcaseStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_status.id
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_status.name
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_status.code
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_status.description
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_status.id
     *
     * @return the value of case_status.id
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_status.id
     *
     * @param id the value for case_status.id
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_status.name
     *
     * @return the value of case_status.name
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_status.name
     *
     * @param name the value for case_status.name
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_status.code
     *
     * @return the value of case_status.code
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_status.code
     *
     * @param code the value for case_status.code
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_status.description
     *
     * @return the value of case_status.description
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_status.description
     *
     * @param description the value for case_status.description
     *
     * @mbg.generated Mon Apr 09 13:54:25 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}